[package]
name = "tacospowaaa"
version = "0.2.0"
authors = ["LittleBoxes"]
edition = "2018"

[dependencies]
piston = "0.39.0"
piston_window = "0.85.0"
piston2d-graphics = "0.30.0"
pistoncore-glutin_window = "0.52.0"
piston2d-opengl_graphics = "0.59.0"
rand = "0.6.4"
find_folder = "0.3.0"
